# Required metadata
sonar.projectKey=Foufou-exe_portfolio
sonar.organization=foufou-exe
# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=portfolio
sonar.projectVersion=2026.02

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclusions for files and directories
sonar.exclusions=**/node_modules/**, .nuxt/**, dist/**, .output/**, test/**, **/*.test.ts, **/*.spec.ts,**/components/ui/**, **/*plugins*/**

# TODO: Important: Adjust the path to your lcov report if it's different
sonar.tests=tests/
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.spec.ts
sonar.testExecutionReportPaths=test-report.xml
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.file.suffixes=.ts,.tsx,.vue
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.tsconfigPath=tsconfig.json